name: Deploy

on:
  pull_request:
    types: closed
    branches: main

jobs:
  publish-crate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/publish-rust-crate@v12
        with:
          cargo-token: ${{ secrets.CARGO_TOKEN }}

  tag-and-release:
    runs-on: ubuntu-24.04
    needs: publish-crate
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/tag-and-release@v12
