name: Publish

on:
  pull_request:
    types: [closed]
    branches: main

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/publish-rust-crate@v11
        with:
          cargo-token: ${{ secrets.CARGO_TOKEN }}

  tag-and-release:
    runs-on: ubuntu-24.04
    needs: publish
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/tag-and-release@v11
