name: Publish to crates.io

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check format
        run: cargo fmt --check

      - name: Lint via Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run vanilla tests
        run: cargo test

      - name: Run full tests
        run: cargo test --all-features

      - name: Publish
        run: cargo publish --all-features
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
