name: Verify

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - uses: giancosta86/aurora-github/actions/verify-rust-crate@v11
